config/routes.rb
Rails.application.routes.draw do
  resources :characteristics
  resources :cars do
    resources :comments
  end
  devise_for :users
  get 'terms_and_conditions/index'
  get 'about/index'

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_model_and_brand,
    against: [:model, :brand]
  has_many :characteristic_cars
  has_many :characteristics, through: :characteristic_cars
  has_many :comments
  validates :model, presence: true
  validates :brand, presence: true
  validates :year, presence: true
  validates :autonomy, presence: true
  validates :rental_price, presence: true
  has_one_attached :image_car
end

app/models/characteristic.rb
class Characteristic < ApplicationRecord
  has_many :characteristic_cars
  has_many :cars, through: :characteristic_cars
end

app/models/characteristic_car.rb
class CharacteristicCar < ApplicationRecord
  belongs_to :car
  belongs_to :characteristic
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :comments
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def after_sign_in_path_for(resource)
    cars_path
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: %i[ show edit update destroy ]

  # GET /cars or /cars.json
  def index
    if params[:query].present?
      @cars = Car.includes(:characteristics).search_by_model_and_brand(params[:query])
    else
      @cars = Car.includes(:characteristics).all.order(id: :desc)
    end
    @pagy, @electric_cars = pagy(@cars, items: 10)
  end

  # GET /cars/1 or /cars/1.json
  def show
    @car = Car.includes(:characteristics).find(params[:id])
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = Car.new( model: car_params[:model], brand: car_params[:brand], year: car_params[:year], 
                    autonomy: car_params[:autonomy], rental_price: car_params[:rental_price], 
                    image_car: car_params[:image_car] )
    respond_to do |format|
      if @car.save
        if car_params[:characteristic_ids].present?
          car_params[:characteristic_ids].each do |characteristic_id|
            CharacteristicCar.new(car_id: @car.id, characteristic_id: characteristic_id).save
          end
        end
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:model, :brand, :year, :autonomy, :rental_price, :image_car, characteristic_ids: [])
    end
end

app/controllers/characteristics_controller.rb
class CharacteristicsController < ApplicationController
  before_action :set_characteristic, only: %i[ show edit update destroy ]

  # GET /characteristics or /characteristics.json
  def index
    @characteristics = Characteristic.all
  end

  # GET /characteristics/1 or /characteristics/1.json
  def show
  end

  # GET /characteristics/new
  def new
    @characteristic = Characteristic.new
  end

  # GET /characteristics/1/edit
  def edit
  end

  # POST /characteristics or /characteristics.json
  def create
    @characteristic = Characteristic.new(characteristic_params)

    respond_to do |format|
      if @characteristic.save
        format.html { redirect_to characteristic_url(@characteristic), notice: "Characteristic was successfully created." }
        format.json { render :show, status: :created, location: @characteristic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characteristics/1 or /characteristics/1.json
  def update
    respond_to do |format|
      if @characteristic.update(characteristic_params)
        format.html { redirect_to characteristic_url(@characteristic), notice: "Characteristic was successfully updated." }
        format.json { render :show, status: :ok, location: @characteristic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @characteristic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characteristics/1 or /characteristics/1.json
  def destroy
    @characteristic.destroy

    respond_to do |format|
      format.html { redirect_to characteristics_url, notice: "Characteristic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_characteristic
      @characteristic = Characteristic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def characteristic_params
      params.require(:characteristic).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @comment = @car.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to car_path(@car), notice: 'Comment was successfully created.'
    else
      render 'cars/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/terms_and_conditions_controller.rb
class TermsAndConditionsController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/characteristics_helper.rb
module CharacteristicsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/terms_and_conditions_helper.rb
module TermsAndConditionsHelper
end

app/views/about/index.html.erb
<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Acerca de Nosotros</h1>
        <p class="lead">En EcoDrive, estamos comprometidos con una visión de un futuro sostenible y limpio. Nuestro objetivo es liderar la revolución de la movilidad eléctrica y brindar soluciones amigables con el medio ambiente.</p>
    </div>

    <div class="row">
        <div class="col-md-6">
            <h2>Nuestros Valores</h2>
            <ul>
                <li><strong>Sostenibilidad:</strong> Promovemos un estilo de vida sostenible y reducimos la huella de carbono.</li>
                <li><strong>Innovación:</strong> Impulsamos la innovación en tecnología de vehículos eléctricos y movilidad.</li>
                <li><strong>Calidad:</strong> Ofrecemos productos y servicios de alta calidad que superan las expectativas de nuestros clientes.</li>
            </ul>
        </div>
        <div class="col-md-6">
            <h2>Nuestros Objetivos</h2>
            <p>Nuestro principal objetivo es facilitar la transición a la movilidad eléctrica para todos. Buscamos:</p>
            <ul>
                <li>Promover el uso de vehículos eléctricos como una alternativa sostenible al transporte convencional.</li>
                <li>Construir una flota diversa y eficiente de autos eléctricos para satisfacer las necesidades de nuestros clientes.</li>
                <li>Brindar una experiencia de conducción cómoda, conveniente y respetuosa con el medio ambiente.</li>
            </ul>
        </div>
    </div>
</div>

app/views/cars/_car.html.erb
<div class="container">
  <div id="<%= dom_id car %>" class="card mb-3">
    <div class="card-img-top">
      <% if car.image_car.attached? %>
        <%= image_tag car.image_car, class: "img-thumbnail", alt: "Imagen del Auto Eléctrico" %>
      <% else %>
        <%= image_tag "default.jpg", class: "img-thumbnail", alt: "Imagen por defecto" %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title">Car Information</h5>
      <p class="card-text">
        <strong>Model:</strong>
        <%= car.model %>
      </p>
      <p class="card-text">
        <strong>Brand:</strong>
        <%= car.brand %>
      </p>
      <p class="card-text">
        <strong>Year:</strong>
        <%= car.year %>
      </p>
      <p class="card-text">
        <strong>Autonomy:</strong>
        <%= car.autonomy %> km
      </p>
      <p class="card-text">
        <strong>Rental Price:</strong>
        $<%= car.rental_price %> per day
      </p>
      <p class="card-text">
        <strong>characteristics:</strong>
        <% car.characteristics.each do |characteristic| %>
          <span class="badge badge-warning text-dark"><%= characteristic.name %></span>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/cars/_form.html.erb
<div class="container">
  <%= form_with(model: car, local: true, html: { multipart: true }) do |form| %>
    <% if car.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>
        <ul>
          <% car.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :model %>
      <%= form.text_field :model, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :brand %>
      <%= form.text_field :brand, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :year %>
      <%= form.number_field :year, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :autonomy %>
      <%= form.number_field :autonomy, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :rental_price %>
      <%= form.text_field :rental_price, class: "form-control" %>
    </div>

    <div class="form-group mt-2">
      <%= form.label :image_car %>
      <%= form.file_field :image_car, class: "form-control-file" %>
    </div>

    <div class="form-group mt-2">
      <%= form.label :characteristic_ids %>
      <%= form.collection_select :characteristic_ids, Characteristic.all, :id, :name, {}, { multiple: true, class: "form-control" } %>
    </div>

    <div class="form-group mt-4">
      <%= form.submit "Guardar", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/cars/edit.html.erb
<div class="container">
  <h1>Editing car</h1>
</div>
<%= render "form", car: @car %>

<br>
<div class="container">
  <%= link_to "Show this car", @car, class: "btn btn-primary mr-2" %>
  <%= link_to "Back to cars", cars_path, class: "btn btn-secondary" %>
</div>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<%= form_tag(cars_path, method: :get) do %>
  <div class="input-group mb-3">
    <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Buscar autos..." %>
    <div class="input-group-append">
      <%= submit_tag "Buscar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>


  <h1>Lista de Autos Eléctricos</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Modelo</th>
        <th>Marca</th>
        <th>Año de Fabricación</th>
        <th>Imagen del Auto Eléctrico</th>
        <th>Caracteristicas</th>
        <th>Perfil</th>
        <th>Editar</th>
      </tr>
    </thead>
<tbody>
  <% @electric_cars.each do |electric_car| %>
    <tr>
      <td><%= electric_car.model %></td>
      <td><%= electric_car.brand %></td>
      <td><%= electric_car.year %></td>
      <td>
        <% if electric_car.image_car.attached? %>
          <%= image_tag electric_car.image_car, class: "img-thumbnail", alt: "Imagen del Auto Eléctrico" %>
        <% else %>
          <%= image_tag "default.jpg", class: "img-thumbnail", alt: "Imagen por defecto" %>
        <% end %>
      </td>
      <td>
        <% electric_car.characteristics.each do |characteristic| %>
          <span class="badge badge-warning text-dark"><%= characteristic.name %></span>
        <% end %>
      <td>
        <% if current_user.role == "client" %>
          <%= link_to "Ver Perfil", car_path(electric_car), class: "btn btn-primary" %>
        <% else %>
          <p>Debes ser un cliente para ver el perfil</p>
        <% end %>
      </td>
      <td>
        <% if current_user.role == "administrator" %>
          <%= link_to "Editar", edit_car_path(electric_car), class: "btn btn-warning" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

  </table>
  <div class="d-flex justify-content-center align-items-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <%if current_user.role == "administrator"%>
    <%= link_to "New car", new_car_path, class: "btn btn-primary" %>
  <%end%>
</div>

app/views/cars/new.html.erb
<div class="container">
  <h1>New car</h1>

  <%= render "form", car: @car %>

  <br>

<div class="mt-3">
  <%= link_to "Back to cars", cars_path, class: "btn btn-primary" %>
</div>

</div>

app/views/cars/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @car %>

<div class="container">
  <h2>Comments</h2>
  <% @car.comments.each do |comment| %>
    <div class="card mt-2">
      <div class="card-body">
        <strong><%= comment.user.email %>:</strong>
        <%= comment.body %>
      </div>
    </div>
  <% end %>

<h2>Add a Comment</h2>
<%= form_with(model: [@car, Comment.new], local: true) do |form| %>
  <div class="form-group">
    <%= form.text_area :body, class: "form-control", placeholder: "Add a comment" %>
  </div>
  <div class="form-group mt-3">
    <%= form.submit "Add Comment", class: "btn btn-primary" %>
  </div>
<% end %>

</div>
<div class="container mt-5 d-flex gap-2">
  <%if current_user.role == "administrator"%>
    <%= link_to "Edit this car", edit_car_path(@car), class: "btn btn-primary mr-2" %>
    <%= button_to "Destroy this car", @car, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <%end%>
  <%= link_to "Back to cars", cars_path, class: "btn btn-secondary mr-2" %>
</div>

app/views/characteristics/_characteristic.html.erb
<div id="<%= dom_id characteristic %>">
  <p>
    <strong>Name:</strong>
    <%= characteristic.name %>
  </p>

</div>

app/views/characteristics/_form.html.erb
<%= form_with(model: characteristic) do |form| %>
  <% if characteristic.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(characteristic.errors.count, "error") %> prohibited this characteristic from being saved:</h2>

      <ul>
        <% characteristic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/characteristics/edit.html.erb
<h1>Editing characteristic</h1>

<%= render "form", characteristic: @characteristic %>

<br>

<div>
  <%= link_to "Show this characteristic", @characteristic %> |
  <%= link_to "Back to characteristics", characteristics_path %>
</div>

app/views/characteristics/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Characteristics</h1>

<div id="characteristics">
  <% @characteristics.each do |characteristic| %>
    <%= render characteristic %>
    <p>
      <%= link_to "Show this characteristic", characteristic %>
    </p>
  <% end %>
</div>

<%= link_to "New characteristic", new_characteristic_path %>

app/views/characteristics/new.html.erb
<h1>New characteristic</h1>

<%= render "form", characteristic: @characteristic %>

<br>

<div>
  <%= link_to "Back to characteristics", characteristics_path %>
</div>

app/views/characteristics/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @characteristic %>

<div>
  <%= link_to "Edit this characteristic", edit_characteristic_path(@characteristic) %> |
  <%= link_to "Back to characteristics", characteristics_path %>

  <%= button_to "Destroy this characteristic", @characteristic, method: :delete %>
</div>

app/views/home/index.html.erb
<%# app/views/home/home.html.erb %>

<div class="container text-center mt-5">
  <h1 class="display-4">¡Bienvenido a la Revolución Eléctrica!</h1>
  <p class="lead">Descubre nuestra flota de autos eléctricos de alta tecnología.</p>
</div>

<div id="carouselExample" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "car1.jpeg", class: "d-block w-100", alt: "Auto Eléctrico 1" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "descarga.jpeg", class: "d-block w-100", alt: "Auto Eléctrico 2" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "descarga2.jpeg", class: "d-block w-100", alt: "Auto Eléctrico 3" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Anterior</span>
  </a>
  <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Siguiente</span>
  </a>
</div>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-4">
      <h2>Características Destacadas</h2>
      <ul>
        <li>Batería de iones de litio</li>
        <li>Tecnología de Asistencia a la Conducción</li>
        <li>Rango de Conducción Sostenible</li>
      </ul>
    </div>
    <div class="col-md-8">
      <h2>Suscríbete a Nuestras Novedades</h2>
      <p>Recibe información sobre nuestros nuevos modelos y ofertas especiales.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcoDrive</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Inicio</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="<%= terms_and_conditions_index_path %>">Términos y Condiciones</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= about_index_path %>">Acerca de Nosotros</a>
                </li>
                <li class="nav-item">
                    <% if user_signed_in? %>
                        <a class="nav-link" href="<%= destroy_user_session_path %>" method="delete" rel="nofollow">Cerrar Sesión</a>
                    <% else %>
                        <a class="nav-link" href="<%= new_user_session_path %>">Iniciar Sesión</a>
                    <% end %>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<%= new_user_registration_path %>">Registrarse</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/terms_and_conditions/index.html.erb
<div class="container">
    <h1 class="mt-5">Términos y Condiciones</h1>
    <p class="lead">Por favor, lea atentamente los siguientes términos y condiciones antes de utilizar nuestro servicio.</p>

    <h2>1. Aceptación de los Términos</h2>
    <p>Al utilizar este servicio, usted acepta estar sujeto a estos términos y condiciones. Si no está de acuerdo con alguno de los términos, por favor no utilice el servicio.</p>

    <h2>2. Uso Apropiado</h2>
    <p>Usted se compromete a utilizar este servicio de manera apropiada y cumplir con todas las leyes y regulaciones aplicables.</p>

    <h2>3. Privacidad</h2>
    <p>Nuestra política de privacidad describe cómo recopilamos, utilizamos y protegemos sus datos personales. Al utilizar nuestro servicio, usted acepta nuestra política de privacidad.</p>

    <h2>4. Cambios en los Términos</h2>
    <p>Nos reservamos el derecho de modificar estos términos en cualquier momento. Los cambios serán efectivos inmediatamente después de su publicación en este sitio web.</p>

    <h2>5. Contacto</h2>
    <p>Si tiene alguna pregunta o inquietud con respecto a estos términos y condiciones, por favor contáctenos a través de la información de contacto proporcionada en nuestro sitio web.</p>

    <p class="text-muted mt-5">Última actualización: 26 de octubre de 2023</p>
</div>